/*
XMS API

Testing CryptoKeysAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CryptoKeysAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CryptoKeysAPIService CreateCryptoKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CryptoKeysAPI.CreateCryptoKey(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CryptoKeysAPIService DownloadCryptoKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyId int64

		resp, httpRes, err := apiClient.CryptoKeysAPI.DownloadCryptoKey(context.Background(), keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CryptoKeysAPIService GetCryptoKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyId int64

		resp, httpRes, err := apiClient.CryptoKeysAPI.GetCryptoKey(context.Background(), keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CryptoKeysAPIService ListCryptoKeys", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CryptoKeysAPI.ListCryptoKeys(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CryptoKeysAPIService UpdateCryptoKey", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyId int64

		resp, httpRes, err := apiClient.CryptoKeysAPI.UpdateCryptoKey(context.Background(), keyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
