/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// NetworkDiagnosisItemsAPIService NetworkDiagnosisItemsAPI service
type NetworkDiagnosisItemsAPIService service

type ApiListNetworkDiagnosisItemsRequest struct {
	ctx context.Context
	ApiService *NetworkDiagnosisItemsAPIService
	limit *int64
	offset *int64
	networks *string
	finished *bool
}

// paging param
func (r ApiListNetworkDiagnosisItemsRequest) Limit(limit int64) ApiListNetworkDiagnosisItemsRequest {
	r.limit = &limit
	return r
}

// paging param
func (r ApiListNetworkDiagnosisItemsRequest) Offset(offset int64) ApiListNetworkDiagnosisItemsRequest {
	r.offset = &offset
	return r
}

// network type
func (r ApiListNetworkDiagnosisItemsRequest) Networks(networks string) ApiListNetworkDiagnosisItemsRequest {
	r.networks = &networks
	return r
}

// diagnosis item finished or not
func (r ApiListNetworkDiagnosisItemsRequest) Finished(finished bool) ApiListNetworkDiagnosisItemsRequest {
	r.finished = &finished
	return r
}

func (r ApiListNetworkDiagnosisItemsRequest) Execute() (*NetworkDiagnosisItemsResp, *http.Response, error) {
	return r.ApiService.ListNetworkDiagnosisItemsExecute(r)
}

/*
ListNetworkDiagnosisItems Method for ListNetworkDiagnosisItems

List network diagnosis items

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListNetworkDiagnosisItemsRequest
*/
func (a *NetworkDiagnosisItemsAPIService) ListNetworkDiagnosisItems(ctx context.Context) ApiListNetworkDiagnosisItemsRequest {
	return ApiListNetworkDiagnosisItemsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return NetworkDiagnosisItemsResp
func (a *NetworkDiagnosisItemsAPIService) ListNetworkDiagnosisItemsExecute(r ApiListNetworkDiagnosisItemsRequest) (*NetworkDiagnosisItemsResp, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *NetworkDiagnosisItemsResp
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NetworkDiagnosisItemsAPIService.ListNetworkDiagnosisItems")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/network-diagnosis-items/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	if r.networks != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "networks", r.networks, "form", "")
	}
	if r.finished != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "finished", r.finished, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["tokenInHeader"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Xms-Auth-Token"] = key
			}
		}
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["tokenInQuery"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarQueryParams.Add("token", key)
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
