/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DfsDirectoriesResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DfsDirectoriesResp{}

// DfsDirectoriesResp struct for DfsDirectoriesResp
type DfsDirectoriesResp struct {
	DfsDirectories DfsDirectoriesRespDirectories `json:"dfs_directories"`
}

type _DfsDirectoriesResp DfsDirectoriesResp

// NewDfsDirectoriesResp instantiates a new DfsDirectoriesResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDfsDirectoriesResp(dfsDirectories DfsDirectoriesRespDirectories) *DfsDirectoriesResp {
	this := DfsDirectoriesResp{}
	this.DfsDirectories = dfsDirectories
	return &this
}

// NewDfsDirectoriesRespWithDefaults instantiates a new DfsDirectoriesResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDfsDirectoriesRespWithDefaults() *DfsDirectoriesResp {
	this := DfsDirectoriesResp{}
	return &this
}

// GetDfsDirectories returns the DfsDirectories field value
func (o *DfsDirectoriesResp) GetDfsDirectories() DfsDirectoriesRespDirectories {
	if o == nil {
		var ret DfsDirectoriesRespDirectories
		return ret
	}

	return o.DfsDirectories
}

// GetDfsDirectoriesOk returns a tuple with the DfsDirectories field value
// and a boolean to check if the value has been set.
func (o *DfsDirectoriesResp) GetDfsDirectoriesOk() (*DfsDirectoriesRespDirectories, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DfsDirectories, true
}

// SetDfsDirectories sets field value
func (o *DfsDirectoriesResp) SetDfsDirectories(v DfsDirectoriesRespDirectories) {
	o.DfsDirectories = v
}

func (o DfsDirectoriesResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DfsDirectoriesResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dfs_directories"] = o.DfsDirectories
	return toSerialize, nil
}

func (o *DfsDirectoriesResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dfs_directories",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDfsDirectoriesResp := _DfsDirectoriesResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDfsDirectoriesResp)

	if err != nil {
		return err
	}

	*o = DfsDirectoriesResp(varDfsDirectoriesResp)

	return err
}

type NullableDfsDirectoriesResp struct {
	value *DfsDirectoriesResp
	isSet bool
}

func (v NullableDfsDirectoriesResp) Get() *DfsDirectoriesResp {
	return v.value
}

func (v *NullableDfsDirectoriesResp) Set(val *DfsDirectoriesResp) {
	v.value = val
	v.isSet = true
}

func (v NullableDfsDirectoriesResp) IsSet() bool {
	return v.isSet
}

func (v *NullableDfsDirectoriesResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDfsDirectoriesResp(val *DfsDirectoriesResp) *NullableDfsDirectoriesResp {
	return &NullableDfsDirectoriesResp{value: val, isSet: true}
}

func (v NullableDfsDirectoriesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDfsDirectoriesResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


