/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DfsRootfsResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DfsRootfsResp{}

// DfsRootfsResp struct for DfsRootfsResp
type DfsRootfsResp struct {
	DfsRootfs DfsRootfsRecord `json:"dfs_rootfs"`
}

type _DfsRootfsResp DfsRootfsResp

// NewDfsRootfsResp instantiates a new DfsRootfsResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDfsRootfsResp(dfsRootfs DfsRootfsRecord) *DfsRootfsResp {
	this := DfsRootfsResp{}
	this.DfsRootfs = dfsRootfs
	return &this
}

// NewDfsRootfsRespWithDefaults instantiates a new DfsRootfsResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDfsRootfsRespWithDefaults() *DfsRootfsResp {
	this := DfsRootfsResp{}
	return &this
}

// GetDfsRootfs returns the DfsRootfs field value
func (o *DfsRootfsResp) GetDfsRootfs() DfsRootfsRecord {
	if o == nil {
		var ret DfsRootfsRecord
		return ret
	}

	return o.DfsRootfs
}

// GetDfsRootfsOk returns a tuple with the DfsRootfs field value
// and a boolean to check if the value has been set.
func (o *DfsRootfsResp) GetDfsRootfsOk() (*DfsRootfsRecord, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DfsRootfs, true
}

// SetDfsRootfs sets field value
func (o *DfsRootfsResp) SetDfsRootfs(v DfsRootfsRecord) {
	o.DfsRootfs = v
}

func (o DfsRootfsResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DfsRootfsResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dfs_rootfs"] = o.DfsRootfs
	return toSerialize, nil
}

func (o *DfsRootfsResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dfs_rootfs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDfsRootfsResp := _DfsRootfsResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDfsRootfsResp)

	if err != nil {
		return err
	}

	*o = DfsRootfsResp(varDfsRootfsResp)

	return err
}

type NullableDfsRootfsResp struct {
	value *DfsRootfsResp
	isSet bool
}

func (v NullableDfsRootfsResp) Get() *DfsRootfsResp {
	return v.value
}

func (v *NullableDfsRootfsResp) Set(val *DfsRootfsResp) {
	v.value = val
	v.isSet = true
}

func (v NullableDfsRootfsResp) IsSet() bool {
	return v.isSet
}

func (v *NullableDfsRootfsResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDfsRootfsResp(val *DfsRootfsResp) *NullableDfsRootfsResp {
	return &NullableDfsRootfsResp{value: val, isSet: true}
}

func (v NullableDfsRootfsResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDfsRootfsResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


