/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DpGatewayResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DpGatewayResp{}

// DpGatewayResp struct for DpGatewayResp
type DpGatewayResp struct {
	DpGateway DpGateway `json:"dp_gateway"`
}

type _DpGatewayResp DpGatewayResp

// NewDpGatewayResp instantiates a new DpGatewayResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDpGatewayResp(dpGateway DpGateway) *DpGatewayResp {
	this := DpGatewayResp{}
	this.DpGateway = dpGateway
	return &this
}

// NewDpGatewayRespWithDefaults instantiates a new DpGatewayResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDpGatewayRespWithDefaults() *DpGatewayResp {
	this := DpGatewayResp{}
	return &this
}

// GetDpGateway returns the DpGateway field value
func (o *DpGatewayResp) GetDpGateway() DpGateway {
	if o == nil {
		var ret DpGateway
		return ret
	}

	return o.DpGateway
}

// GetDpGatewayOk returns a tuple with the DpGateway field value
// and a boolean to check if the value has been set.
func (o *DpGatewayResp) GetDpGatewayOk() (*DpGateway, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DpGateway, true
}

// SetDpGateway sets field value
func (o *DpGatewayResp) SetDpGateway(v DpGateway) {
	o.DpGateway = v
}

func (o DpGatewayResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DpGatewayResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dp_gateway"] = o.DpGateway
	return toSerialize, nil
}

func (o *DpGatewayResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dp_gateway",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDpGatewayResp := _DpGatewayResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDpGatewayResp)

	if err != nil {
		return err
	}

	*o = DpGatewayResp(varDpGatewayResp)

	return err
}

type NullableDpGatewayResp struct {
	value *DpGatewayResp
	isSet bool
}

func (v NullableDpGatewayResp) Get() *DpGatewayResp {
	return v.value
}

func (v *NullableDpGatewayResp) Set(val *DpGatewayResp) {
	v.value = val
	v.isSet = true
}

func (v NullableDpGatewayResp) IsSet() bool {
	return v.isSet
}

func (v *NullableDpGatewayResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDpGatewayResp(val *DpGatewayResp) *NullableDpGatewayResp {
	return &NullableDpGatewayResp{value: val, isSet: true}
}

func (v NullableDpGatewayResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDpGatewayResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


