/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the S3LoadBalancerGroupNestview type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3LoadBalancerGroupNestview{}

// S3LoadBalancerGroupNestview struct for S3LoadBalancerGroupNestview
type S3LoadBalancerGroupNestview struct {
	Id *int64 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewS3LoadBalancerGroupNestview instantiates a new S3LoadBalancerGroupNestview object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3LoadBalancerGroupNestview() *S3LoadBalancerGroupNestview {
	this := S3LoadBalancerGroupNestview{}
	return &this
}

// NewS3LoadBalancerGroupNestviewWithDefaults instantiates a new S3LoadBalancerGroupNestview object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3LoadBalancerGroupNestviewWithDefaults() *S3LoadBalancerGroupNestview {
	this := S3LoadBalancerGroupNestview{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *S3LoadBalancerGroupNestview) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3LoadBalancerGroupNestview) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *S3LoadBalancerGroupNestview) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *S3LoadBalancerGroupNestview) SetId(v int64) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *S3LoadBalancerGroupNestview) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3LoadBalancerGroupNestview) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *S3LoadBalancerGroupNestview) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *S3LoadBalancerGroupNestview) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *S3LoadBalancerGroupNestview) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *S3LoadBalancerGroupNestview) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *S3LoadBalancerGroupNestview) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *S3LoadBalancerGroupNestview) SetStatus(v string) {
	o.Status = &v
}

func (o S3LoadBalancerGroupNestview) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3LoadBalancerGroupNestview) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableS3LoadBalancerGroupNestview struct {
	value *S3LoadBalancerGroupNestview
	isSet bool
}

func (v NullableS3LoadBalancerGroupNestview) Get() *S3LoadBalancerGroupNestview {
	return v.value
}

func (v *NullableS3LoadBalancerGroupNestview) Set(val *S3LoadBalancerGroupNestview) {
	v.value = val
	v.isSet = true
}

func (v NullableS3LoadBalancerGroupNestview) IsSet() bool {
	return v.isSet
}

func (v *NullableS3LoadBalancerGroupNestview) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3LoadBalancerGroupNestview(val *S3LoadBalancerGroupNestview) *NullableS3LoadBalancerGroupNestview {
	return &NullableS3LoadBalancerGroupNestview{value: val, isSet: true}
}

func (v NullableS3LoadBalancerGroupNestview) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3LoadBalancerGroupNestview) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


