/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the NetworkDiagnosisItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkDiagnosisItem{}

// NetworkDiagnosisItem NetworkDiagnosisItem defines model of network diagnosis item
type NetworkDiagnosisItem struct {
	Create *time.Time `json:"create,omitempty"`
	DstHost *HostNestview `json:"dst_host,omitempty"`
	DstInterface *string `json:"dst_interface,omitempty"`
	DstIp *string `json:"dst_ip,omitempty"`
	DstMegabits *int64 `json:"dst_megabits,omitempty"`
	DstType *string `json:"dst_type,omitempty"`
	Execute *time.Time `json:"execute,omitempty"`
	Finish *time.Time `json:"finish,omitempty"`
	Id *int64 `json:"id,omitempty"`
	Message *string `json:"message,omitempty"`
	NetworkDiagnosis *NetworkDiagnosisNestview `json:"network_diagnosis,omitempty"`
	Networks []string `json:"networks,omitempty"`
	SrcHost *HostNestview `json:"src_host,omitempty"`
	SrcInterface *string `json:"src_interface,omitempty"`
	SrcIp *string `json:"src_ip,omitempty"`
	SrcMegabits *int64 `json:"src_megabits,omitempty"`
	SrcType *string `json:"src_type,omitempty"`
	Stat *NetworkDiagnosisStat `json:"stat,omitempty"`
	Status *string `json:"status,omitempty"`
	Update *time.Time `json:"update,omitempty"`
}

// NewNetworkDiagnosisItem instantiates a new NetworkDiagnosisItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkDiagnosisItem() *NetworkDiagnosisItem {
	this := NetworkDiagnosisItem{}
	return &this
}

// NewNetworkDiagnosisItemWithDefaults instantiates a new NetworkDiagnosisItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkDiagnosisItemWithDefaults() *NetworkDiagnosisItem {
	this := NetworkDiagnosisItem{}
	return &this
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetCreate() time.Time {
	if o == nil || IsNil(o.Create) {
		var ret time.Time
		return ret
	}
	return *o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetCreateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Create) {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasCreate() bool {
	if o != nil && !IsNil(o.Create) {
		return true
	}

	return false
}

// SetCreate gets a reference to the given time.Time and assigns it to the Create field.
func (o *NetworkDiagnosisItem) SetCreate(v time.Time) {
	o.Create = &v
}

// GetDstHost returns the DstHost field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetDstHost() HostNestview {
	if o == nil || IsNil(o.DstHost) {
		var ret HostNestview
		return ret
	}
	return *o.DstHost
}

// GetDstHostOk returns a tuple with the DstHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetDstHostOk() (*HostNestview, bool) {
	if o == nil || IsNil(o.DstHost) {
		return nil, false
	}
	return o.DstHost, true
}

// HasDstHost returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasDstHost() bool {
	if o != nil && !IsNil(o.DstHost) {
		return true
	}

	return false
}

// SetDstHost gets a reference to the given HostNestview and assigns it to the DstHost field.
func (o *NetworkDiagnosisItem) SetDstHost(v HostNestview) {
	o.DstHost = &v
}

// GetDstInterface returns the DstInterface field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetDstInterface() string {
	if o == nil || IsNil(o.DstInterface) {
		var ret string
		return ret
	}
	return *o.DstInterface
}

// GetDstInterfaceOk returns a tuple with the DstInterface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetDstInterfaceOk() (*string, bool) {
	if o == nil || IsNil(o.DstInterface) {
		return nil, false
	}
	return o.DstInterface, true
}

// HasDstInterface returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasDstInterface() bool {
	if o != nil && !IsNil(o.DstInterface) {
		return true
	}

	return false
}

// SetDstInterface gets a reference to the given string and assigns it to the DstInterface field.
func (o *NetworkDiagnosisItem) SetDstInterface(v string) {
	o.DstInterface = &v
}

// GetDstIp returns the DstIp field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetDstIp() string {
	if o == nil || IsNil(o.DstIp) {
		var ret string
		return ret
	}
	return *o.DstIp
}

// GetDstIpOk returns a tuple with the DstIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetDstIpOk() (*string, bool) {
	if o == nil || IsNil(o.DstIp) {
		return nil, false
	}
	return o.DstIp, true
}

// HasDstIp returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasDstIp() bool {
	if o != nil && !IsNil(o.DstIp) {
		return true
	}

	return false
}

// SetDstIp gets a reference to the given string and assigns it to the DstIp field.
func (o *NetworkDiagnosisItem) SetDstIp(v string) {
	o.DstIp = &v
}

// GetDstMegabits returns the DstMegabits field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetDstMegabits() int64 {
	if o == nil || IsNil(o.DstMegabits) {
		var ret int64
		return ret
	}
	return *o.DstMegabits
}

// GetDstMegabitsOk returns a tuple with the DstMegabits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetDstMegabitsOk() (*int64, bool) {
	if o == nil || IsNil(o.DstMegabits) {
		return nil, false
	}
	return o.DstMegabits, true
}

// HasDstMegabits returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasDstMegabits() bool {
	if o != nil && !IsNil(o.DstMegabits) {
		return true
	}

	return false
}

// SetDstMegabits gets a reference to the given int64 and assigns it to the DstMegabits field.
func (o *NetworkDiagnosisItem) SetDstMegabits(v int64) {
	o.DstMegabits = &v
}

// GetDstType returns the DstType field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetDstType() string {
	if o == nil || IsNil(o.DstType) {
		var ret string
		return ret
	}
	return *o.DstType
}

// GetDstTypeOk returns a tuple with the DstType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetDstTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DstType) {
		return nil, false
	}
	return o.DstType, true
}

// HasDstType returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasDstType() bool {
	if o != nil && !IsNil(o.DstType) {
		return true
	}

	return false
}

// SetDstType gets a reference to the given string and assigns it to the DstType field.
func (o *NetworkDiagnosisItem) SetDstType(v string) {
	o.DstType = &v
}

// GetExecute returns the Execute field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetExecute() time.Time {
	if o == nil || IsNil(o.Execute) {
		var ret time.Time
		return ret
	}
	return *o.Execute
}

// GetExecuteOk returns a tuple with the Execute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetExecuteOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Execute) {
		return nil, false
	}
	return o.Execute, true
}

// HasExecute returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasExecute() bool {
	if o != nil && !IsNil(o.Execute) {
		return true
	}

	return false
}

// SetExecute gets a reference to the given time.Time and assigns it to the Execute field.
func (o *NetworkDiagnosisItem) SetExecute(v time.Time) {
	o.Execute = &v
}

// GetFinish returns the Finish field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetFinish() time.Time {
	if o == nil || IsNil(o.Finish) {
		var ret time.Time
		return ret
	}
	return *o.Finish
}

// GetFinishOk returns a tuple with the Finish field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetFinishOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Finish) {
		return nil, false
	}
	return o.Finish, true
}

// HasFinish returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasFinish() bool {
	if o != nil && !IsNil(o.Finish) {
		return true
	}

	return false
}

// SetFinish gets a reference to the given time.Time and assigns it to the Finish field.
func (o *NetworkDiagnosisItem) SetFinish(v time.Time) {
	o.Finish = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *NetworkDiagnosisItem) SetId(v int64) {
	o.Id = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *NetworkDiagnosisItem) SetMessage(v string) {
	o.Message = &v
}

// GetNetworkDiagnosis returns the NetworkDiagnosis field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetNetworkDiagnosis() NetworkDiagnosisNestview {
	if o == nil || IsNil(o.NetworkDiagnosis) {
		var ret NetworkDiagnosisNestview
		return ret
	}
	return *o.NetworkDiagnosis
}

// GetNetworkDiagnosisOk returns a tuple with the NetworkDiagnosis field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetNetworkDiagnosisOk() (*NetworkDiagnosisNestview, bool) {
	if o == nil || IsNil(o.NetworkDiagnosis) {
		return nil, false
	}
	return o.NetworkDiagnosis, true
}

// HasNetworkDiagnosis returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasNetworkDiagnosis() bool {
	if o != nil && !IsNil(o.NetworkDiagnosis) {
		return true
	}

	return false
}

// SetNetworkDiagnosis gets a reference to the given NetworkDiagnosisNestview and assigns it to the NetworkDiagnosis field.
func (o *NetworkDiagnosisItem) SetNetworkDiagnosis(v NetworkDiagnosisNestview) {
	o.NetworkDiagnosis = &v
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetNetworks() []string {
	if o == nil || IsNil(o.Networks) {
		var ret []string
		return ret
	}
	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetNetworksOk() ([]string, bool) {
	if o == nil || IsNil(o.Networks) {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given []string and assigns it to the Networks field.
func (o *NetworkDiagnosisItem) SetNetworks(v []string) {
	o.Networks = v
}

// GetSrcHost returns the SrcHost field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetSrcHost() HostNestview {
	if o == nil || IsNil(o.SrcHost) {
		var ret HostNestview
		return ret
	}
	return *o.SrcHost
}

// GetSrcHostOk returns a tuple with the SrcHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetSrcHostOk() (*HostNestview, bool) {
	if o == nil || IsNil(o.SrcHost) {
		return nil, false
	}
	return o.SrcHost, true
}

// HasSrcHost returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasSrcHost() bool {
	if o != nil && !IsNil(o.SrcHost) {
		return true
	}

	return false
}

// SetSrcHost gets a reference to the given HostNestview and assigns it to the SrcHost field.
func (o *NetworkDiagnosisItem) SetSrcHost(v HostNestview) {
	o.SrcHost = &v
}

// GetSrcInterface returns the SrcInterface field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetSrcInterface() string {
	if o == nil || IsNil(o.SrcInterface) {
		var ret string
		return ret
	}
	return *o.SrcInterface
}

// GetSrcInterfaceOk returns a tuple with the SrcInterface field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetSrcInterfaceOk() (*string, bool) {
	if o == nil || IsNil(o.SrcInterface) {
		return nil, false
	}
	return o.SrcInterface, true
}

// HasSrcInterface returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasSrcInterface() bool {
	if o != nil && !IsNil(o.SrcInterface) {
		return true
	}

	return false
}

// SetSrcInterface gets a reference to the given string and assigns it to the SrcInterface field.
func (o *NetworkDiagnosisItem) SetSrcInterface(v string) {
	o.SrcInterface = &v
}

// GetSrcIp returns the SrcIp field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetSrcIp() string {
	if o == nil || IsNil(o.SrcIp) {
		var ret string
		return ret
	}
	return *o.SrcIp
}

// GetSrcIpOk returns a tuple with the SrcIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetSrcIpOk() (*string, bool) {
	if o == nil || IsNil(o.SrcIp) {
		return nil, false
	}
	return o.SrcIp, true
}

// HasSrcIp returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasSrcIp() bool {
	if o != nil && !IsNil(o.SrcIp) {
		return true
	}

	return false
}

// SetSrcIp gets a reference to the given string and assigns it to the SrcIp field.
func (o *NetworkDiagnosisItem) SetSrcIp(v string) {
	o.SrcIp = &v
}

// GetSrcMegabits returns the SrcMegabits field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetSrcMegabits() int64 {
	if o == nil || IsNil(o.SrcMegabits) {
		var ret int64
		return ret
	}
	return *o.SrcMegabits
}

// GetSrcMegabitsOk returns a tuple with the SrcMegabits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetSrcMegabitsOk() (*int64, bool) {
	if o == nil || IsNil(o.SrcMegabits) {
		return nil, false
	}
	return o.SrcMegabits, true
}

// HasSrcMegabits returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasSrcMegabits() bool {
	if o != nil && !IsNil(o.SrcMegabits) {
		return true
	}

	return false
}

// SetSrcMegabits gets a reference to the given int64 and assigns it to the SrcMegabits field.
func (o *NetworkDiagnosisItem) SetSrcMegabits(v int64) {
	o.SrcMegabits = &v
}

// GetSrcType returns the SrcType field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetSrcType() string {
	if o == nil || IsNil(o.SrcType) {
		var ret string
		return ret
	}
	return *o.SrcType
}

// GetSrcTypeOk returns a tuple with the SrcType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetSrcTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SrcType) {
		return nil, false
	}
	return o.SrcType, true
}

// HasSrcType returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasSrcType() bool {
	if o != nil && !IsNil(o.SrcType) {
		return true
	}

	return false
}

// SetSrcType gets a reference to the given string and assigns it to the SrcType field.
func (o *NetworkDiagnosisItem) SetSrcType(v string) {
	o.SrcType = &v
}

// GetStat returns the Stat field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetStat() NetworkDiagnosisStat {
	if o == nil || IsNil(o.Stat) {
		var ret NetworkDiagnosisStat
		return ret
	}
	return *o.Stat
}

// GetStatOk returns a tuple with the Stat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetStatOk() (*NetworkDiagnosisStat, bool) {
	if o == nil || IsNil(o.Stat) {
		return nil, false
	}
	return o.Stat, true
}

// HasStat returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasStat() bool {
	if o != nil && !IsNil(o.Stat) {
		return true
	}

	return false
}

// SetStat gets a reference to the given NetworkDiagnosisStat and assigns it to the Stat field.
func (o *NetworkDiagnosisItem) SetStat(v NetworkDiagnosisStat) {
	o.Stat = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *NetworkDiagnosisItem) SetStatus(v string) {
	o.Status = &v
}

// GetUpdate returns the Update field value if set, zero value otherwise.
func (o *NetworkDiagnosisItem) GetUpdate() time.Time {
	if o == nil || IsNil(o.Update) {
		var ret time.Time
		return ret
	}
	return *o.Update
}

// GetUpdateOk returns a tuple with the Update field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkDiagnosisItem) GetUpdateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Update) {
		return nil, false
	}
	return o.Update, true
}

// HasUpdate returns a boolean if a field has been set.
func (o *NetworkDiagnosisItem) HasUpdate() bool {
	if o != nil && !IsNil(o.Update) {
		return true
	}

	return false
}

// SetUpdate gets a reference to the given time.Time and assigns it to the Update field.
func (o *NetworkDiagnosisItem) SetUpdate(v time.Time) {
	o.Update = &v
}

func (o NetworkDiagnosisItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkDiagnosisItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Create) {
		toSerialize["create"] = o.Create
	}
	if !IsNil(o.DstHost) {
		toSerialize["dst_host"] = o.DstHost
	}
	if !IsNil(o.DstInterface) {
		toSerialize["dst_interface"] = o.DstInterface
	}
	if !IsNil(o.DstIp) {
		toSerialize["dst_ip"] = o.DstIp
	}
	if !IsNil(o.DstMegabits) {
		toSerialize["dst_megabits"] = o.DstMegabits
	}
	if !IsNil(o.DstType) {
		toSerialize["dst_type"] = o.DstType
	}
	if !IsNil(o.Execute) {
		toSerialize["execute"] = o.Execute
	}
	if !IsNil(o.Finish) {
		toSerialize["finish"] = o.Finish
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.NetworkDiagnosis) {
		toSerialize["network_diagnosis"] = o.NetworkDiagnosis
	}
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if !IsNil(o.SrcHost) {
		toSerialize["src_host"] = o.SrcHost
	}
	if !IsNil(o.SrcInterface) {
		toSerialize["src_interface"] = o.SrcInterface
	}
	if !IsNil(o.SrcIp) {
		toSerialize["src_ip"] = o.SrcIp
	}
	if !IsNil(o.SrcMegabits) {
		toSerialize["src_megabits"] = o.SrcMegabits
	}
	if !IsNil(o.SrcType) {
		toSerialize["src_type"] = o.SrcType
	}
	if !IsNil(o.Stat) {
		toSerialize["stat"] = o.Stat
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Update) {
		toSerialize["update"] = o.Update
	}
	return toSerialize, nil
}

type NullableNetworkDiagnosisItem struct {
	value *NetworkDiagnosisItem
	isSet bool
}

func (v NullableNetworkDiagnosisItem) Get() *NetworkDiagnosisItem {
	return v.value
}

func (v *NullableNetworkDiagnosisItem) Set(val *NetworkDiagnosisItem) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkDiagnosisItem) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkDiagnosisItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkDiagnosisItem(val *NetworkDiagnosisItem) *NullableNetworkDiagnosisItem {
	return &NullableNetworkDiagnosisItem{value: val, isSet: true}
}

func (v NullableNetworkDiagnosisItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkDiagnosisItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


