/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OsdSamplesResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OsdSamplesResp{}

// OsdSamplesResp struct for OsdSamplesResp
type OsdSamplesResp struct {
	// osd samples
	OsdSamples []OsdStat `json:"osd_samples"`
}

type _OsdSamplesResp OsdSamplesResp

// NewOsdSamplesResp instantiates a new OsdSamplesResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOsdSamplesResp(osdSamples []OsdStat) *OsdSamplesResp {
	this := OsdSamplesResp{}
	this.OsdSamples = osdSamples
	return &this
}

// NewOsdSamplesRespWithDefaults instantiates a new OsdSamplesResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOsdSamplesRespWithDefaults() *OsdSamplesResp {
	this := OsdSamplesResp{}
	return &this
}

// GetOsdSamples returns the OsdSamples field value
func (o *OsdSamplesResp) GetOsdSamples() []OsdStat {
	if o == nil {
		var ret []OsdStat
		return ret
	}

	return o.OsdSamples
}

// GetOsdSamplesOk returns a tuple with the OsdSamples field value
// and a boolean to check if the value has been set.
func (o *OsdSamplesResp) GetOsdSamplesOk() ([]OsdStat, bool) {
	if o == nil {
		return nil, false
	}
	return o.OsdSamples, true
}

// SetOsdSamples sets field value
func (o *OsdSamplesResp) SetOsdSamples(v []OsdStat) {
	o.OsdSamples = v
}

func (o OsdSamplesResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OsdSamplesResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["osd_samples"] = o.OsdSamples
	return toSerialize, nil
}

func (o *OsdSamplesResp) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"osd_samples",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOsdSamplesResp := _OsdSamplesResp{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOsdSamplesResp)

	if err != nil {
		return err
	}

	*o = OsdSamplesResp(varOsdSamplesResp)

	return err
}

type NullableOsdSamplesResp struct {
	value *OsdSamplesResp
	isSet bool
}

func (v NullableOsdSamplesResp) Get() *OsdSamplesResp {
	return v.value
}

func (v *NullableOsdSamplesResp) Set(val *OsdSamplesResp) {
	v.value = val
	v.isSet = true
}

func (v NullableOsdSamplesResp) IsSet() bool {
	return v.isSet
}

func (v *NullableOsdSamplesResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOsdSamplesResp(val *OsdSamplesResp) *NullableOsdSamplesResp {
	return &NullableOsdSamplesResp{value: val, isSet: true}
}

func (v NullableOsdSamplesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOsdSamplesResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


