/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FSActiveDirectoryCreateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FSActiveDirectoryCreateReq{}

// FSActiveDirectoryCreateReq struct for FSActiveDirectoryCreateReq
type FSActiveDirectoryCreateReq struct {
	FsActiveDirectory FSActiveDirectoryCreateReqInfo `json:"fs_active_directory"`
}

type _FSActiveDirectoryCreateReq FSActiveDirectoryCreateReq

// NewFSActiveDirectoryCreateReq instantiates a new FSActiveDirectoryCreateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFSActiveDirectoryCreateReq(fsActiveDirectory FSActiveDirectoryCreateReqInfo) *FSActiveDirectoryCreateReq {
	this := FSActiveDirectoryCreateReq{}
	this.FsActiveDirectory = fsActiveDirectory
	return &this
}

// NewFSActiveDirectoryCreateReqWithDefaults instantiates a new FSActiveDirectoryCreateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFSActiveDirectoryCreateReqWithDefaults() *FSActiveDirectoryCreateReq {
	this := FSActiveDirectoryCreateReq{}
	return &this
}

// GetFsActiveDirectory returns the FsActiveDirectory field value
func (o *FSActiveDirectoryCreateReq) GetFsActiveDirectory() FSActiveDirectoryCreateReqInfo {
	if o == nil {
		var ret FSActiveDirectoryCreateReqInfo
		return ret
	}

	return o.FsActiveDirectory
}

// GetFsActiveDirectoryOk returns a tuple with the FsActiveDirectory field value
// and a boolean to check if the value has been set.
func (o *FSActiveDirectoryCreateReq) GetFsActiveDirectoryOk() (*FSActiveDirectoryCreateReqInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FsActiveDirectory, true
}

// SetFsActiveDirectory sets field value
func (o *FSActiveDirectoryCreateReq) SetFsActiveDirectory(v FSActiveDirectoryCreateReqInfo) {
	o.FsActiveDirectory = v
}

func (o FSActiveDirectoryCreateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FSActiveDirectoryCreateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fs_active_directory"] = o.FsActiveDirectory
	return toSerialize, nil
}

func (o *FSActiveDirectoryCreateReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fs_active_directory",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFSActiveDirectoryCreateReq := _FSActiveDirectoryCreateReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFSActiveDirectoryCreateReq)

	if err != nil {
		return err
	}

	*o = FSActiveDirectoryCreateReq(varFSActiveDirectoryCreateReq)

	return err
}

type NullableFSActiveDirectoryCreateReq struct {
	value *FSActiveDirectoryCreateReq
	isSet bool
}

func (v NullableFSActiveDirectoryCreateReq) Get() *FSActiveDirectoryCreateReq {
	return v.value
}

func (v *NullableFSActiveDirectoryCreateReq) Set(val *FSActiveDirectoryCreateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableFSActiveDirectoryCreateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableFSActiveDirectoryCreateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFSActiveDirectoryCreateReq(val *FSActiveDirectoryCreateReq) *NullableFSActiveDirectoryCreateReq {
	return &NullableFSActiveDirectoryCreateReq{value: val, isSet: true}
}

func (v NullableFSActiveDirectoryCreateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFSActiveDirectoryCreateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


