/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BucketFlag type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BucketFlag{}

// BucketFlag BucketFlag is the struct of bucket flag Note: the name of json tag must be consistent with the --bucket-flag parameter value   in radosgw-admin set-flag/remove-flag command
type BucketFlag struct {
	DeleteTriggerArchiveTier *bool `json:"delete_trigger_archive_tier,omitempty"`
	GetTriggerRestore *bool `json:"get_trigger_restore,omitempty"`
	Readonly *bool `json:"readonly,omitempty"`
	Recycle *bool `json:"recycle,omitempty"`
	TierCache *bool `json:"tier_cache,omitempty"`
	// set bucket local delete mode
	TierRetainExternalObject *bool `json:"tier_retain_external_object,omitempty"`
	TierWorm *bool `json:"tier_worm,omitempty"`
	Versioned *bool `json:"versioned,omitempty"`
	VersionsSuspended *bool `json:"versions_suspended,omitempty"`
	Worm *bool `json:"worm,omitempty"`
}

// NewBucketFlag instantiates a new BucketFlag object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBucketFlag() *BucketFlag {
	this := BucketFlag{}
	return &this
}

// NewBucketFlagWithDefaults instantiates a new BucketFlag object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBucketFlagWithDefaults() *BucketFlag {
	this := BucketFlag{}
	return &this
}

// GetDeleteTriggerArchiveTier returns the DeleteTriggerArchiveTier field value if set, zero value otherwise.
func (o *BucketFlag) GetDeleteTriggerArchiveTier() bool {
	if o == nil || IsNil(o.DeleteTriggerArchiveTier) {
		var ret bool
		return ret
	}
	return *o.DeleteTriggerArchiveTier
}

// GetDeleteTriggerArchiveTierOk returns a tuple with the DeleteTriggerArchiveTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetDeleteTriggerArchiveTierOk() (*bool, bool) {
	if o == nil || IsNil(o.DeleteTriggerArchiveTier) {
		return nil, false
	}
	return o.DeleteTriggerArchiveTier, true
}

// HasDeleteTriggerArchiveTier returns a boolean if a field has been set.
func (o *BucketFlag) HasDeleteTriggerArchiveTier() bool {
	if o != nil && !IsNil(o.DeleteTriggerArchiveTier) {
		return true
	}

	return false
}

// SetDeleteTriggerArchiveTier gets a reference to the given bool and assigns it to the DeleteTriggerArchiveTier field.
func (o *BucketFlag) SetDeleteTriggerArchiveTier(v bool) {
	o.DeleteTriggerArchiveTier = &v
}

// GetGetTriggerRestore returns the GetTriggerRestore field value if set, zero value otherwise.
func (o *BucketFlag) GetGetTriggerRestore() bool {
	if o == nil || IsNil(o.GetTriggerRestore) {
		var ret bool
		return ret
	}
	return *o.GetTriggerRestore
}

// GetGetTriggerRestoreOk returns a tuple with the GetTriggerRestore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetGetTriggerRestoreOk() (*bool, bool) {
	if o == nil || IsNil(o.GetTriggerRestore) {
		return nil, false
	}
	return o.GetTriggerRestore, true
}

// HasGetTriggerRestore returns a boolean if a field has been set.
func (o *BucketFlag) HasGetTriggerRestore() bool {
	if o != nil && !IsNil(o.GetTriggerRestore) {
		return true
	}

	return false
}

// SetGetTriggerRestore gets a reference to the given bool and assigns it to the GetTriggerRestore field.
func (o *BucketFlag) SetGetTriggerRestore(v bool) {
	o.GetTriggerRestore = &v
}

// GetReadonly returns the Readonly field value if set, zero value otherwise.
func (o *BucketFlag) GetReadonly() bool {
	if o == nil || IsNil(o.Readonly) {
		var ret bool
		return ret
	}
	return *o.Readonly
}

// GetReadonlyOk returns a tuple with the Readonly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetReadonlyOk() (*bool, bool) {
	if o == nil || IsNil(o.Readonly) {
		return nil, false
	}
	return o.Readonly, true
}

// HasReadonly returns a boolean if a field has been set.
func (o *BucketFlag) HasReadonly() bool {
	if o != nil && !IsNil(o.Readonly) {
		return true
	}

	return false
}

// SetReadonly gets a reference to the given bool and assigns it to the Readonly field.
func (o *BucketFlag) SetReadonly(v bool) {
	o.Readonly = &v
}

// GetRecycle returns the Recycle field value if set, zero value otherwise.
func (o *BucketFlag) GetRecycle() bool {
	if o == nil || IsNil(o.Recycle) {
		var ret bool
		return ret
	}
	return *o.Recycle
}

// GetRecycleOk returns a tuple with the Recycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetRecycleOk() (*bool, bool) {
	if o == nil || IsNil(o.Recycle) {
		return nil, false
	}
	return o.Recycle, true
}

// HasRecycle returns a boolean if a field has been set.
func (o *BucketFlag) HasRecycle() bool {
	if o != nil && !IsNil(o.Recycle) {
		return true
	}

	return false
}

// SetRecycle gets a reference to the given bool and assigns it to the Recycle field.
func (o *BucketFlag) SetRecycle(v bool) {
	o.Recycle = &v
}

// GetTierCache returns the TierCache field value if set, zero value otherwise.
func (o *BucketFlag) GetTierCache() bool {
	if o == nil || IsNil(o.TierCache) {
		var ret bool
		return ret
	}
	return *o.TierCache
}

// GetTierCacheOk returns a tuple with the TierCache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetTierCacheOk() (*bool, bool) {
	if o == nil || IsNil(o.TierCache) {
		return nil, false
	}
	return o.TierCache, true
}

// HasTierCache returns a boolean if a field has been set.
func (o *BucketFlag) HasTierCache() bool {
	if o != nil && !IsNil(o.TierCache) {
		return true
	}

	return false
}

// SetTierCache gets a reference to the given bool and assigns it to the TierCache field.
func (o *BucketFlag) SetTierCache(v bool) {
	o.TierCache = &v
}

// GetTierRetainExternalObject returns the TierRetainExternalObject field value if set, zero value otherwise.
func (o *BucketFlag) GetTierRetainExternalObject() bool {
	if o == nil || IsNil(o.TierRetainExternalObject) {
		var ret bool
		return ret
	}
	return *o.TierRetainExternalObject
}

// GetTierRetainExternalObjectOk returns a tuple with the TierRetainExternalObject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetTierRetainExternalObjectOk() (*bool, bool) {
	if o == nil || IsNil(o.TierRetainExternalObject) {
		return nil, false
	}
	return o.TierRetainExternalObject, true
}

// HasTierRetainExternalObject returns a boolean if a field has been set.
func (o *BucketFlag) HasTierRetainExternalObject() bool {
	if o != nil && !IsNil(o.TierRetainExternalObject) {
		return true
	}

	return false
}

// SetTierRetainExternalObject gets a reference to the given bool and assigns it to the TierRetainExternalObject field.
func (o *BucketFlag) SetTierRetainExternalObject(v bool) {
	o.TierRetainExternalObject = &v
}

// GetTierWorm returns the TierWorm field value if set, zero value otherwise.
func (o *BucketFlag) GetTierWorm() bool {
	if o == nil || IsNil(o.TierWorm) {
		var ret bool
		return ret
	}
	return *o.TierWorm
}

// GetTierWormOk returns a tuple with the TierWorm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetTierWormOk() (*bool, bool) {
	if o == nil || IsNil(o.TierWorm) {
		return nil, false
	}
	return o.TierWorm, true
}

// HasTierWorm returns a boolean if a field has been set.
func (o *BucketFlag) HasTierWorm() bool {
	if o != nil && !IsNil(o.TierWorm) {
		return true
	}

	return false
}

// SetTierWorm gets a reference to the given bool and assigns it to the TierWorm field.
func (o *BucketFlag) SetTierWorm(v bool) {
	o.TierWorm = &v
}

// GetVersioned returns the Versioned field value if set, zero value otherwise.
func (o *BucketFlag) GetVersioned() bool {
	if o == nil || IsNil(o.Versioned) {
		var ret bool
		return ret
	}
	return *o.Versioned
}

// GetVersionedOk returns a tuple with the Versioned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetVersionedOk() (*bool, bool) {
	if o == nil || IsNil(o.Versioned) {
		return nil, false
	}
	return o.Versioned, true
}

// HasVersioned returns a boolean if a field has been set.
func (o *BucketFlag) HasVersioned() bool {
	if o != nil && !IsNil(o.Versioned) {
		return true
	}

	return false
}

// SetVersioned gets a reference to the given bool and assigns it to the Versioned field.
func (o *BucketFlag) SetVersioned(v bool) {
	o.Versioned = &v
}

// GetVersionsSuspended returns the VersionsSuspended field value if set, zero value otherwise.
func (o *BucketFlag) GetVersionsSuspended() bool {
	if o == nil || IsNil(o.VersionsSuspended) {
		var ret bool
		return ret
	}
	return *o.VersionsSuspended
}

// GetVersionsSuspendedOk returns a tuple with the VersionsSuspended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetVersionsSuspendedOk() (*bool, bool) {
	if o == nil || IsNil(o.VersionsSuspended) {
		return nil, false
	}
	return o.VersionsSuspended, true
}

// HasVersionsSuspended returns a boolean if a field has been set.
func (o *BucketFlag) HasVersionsSuspended() bool {
	if o != nil && !IsNil(o.VersionsSuspended) {
		return true
	}

	return false
}

// SetVersionsSuspended gets a reference to the given bool and assigns it to the VersionsSuspended field.
func (o *BucketFlag) SetVersionsSuspended(v bool) {
	o.VersionsSuspended = &v
}

// GetWorm returns the Worm field value if set, zero value otherwise.
func (o *BucketFlag) GetWorm() bool {
	if o == nil || IsNil(o.Worm) {
		var ret bool
		return ret
	}
	return *o.Worm
}

// GetWormOk returns a tuple with the Worm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BucketFlag) GetWormOk() (*bool, bool) {
	if o == nil || IsNil(o.Worm) {
		return nil, false
	}
	return o.Worm, true
}

// HasWorm returns a boolean if a field has been set.
func (o *BucketFlag) HasWorm() bool {
	if o != nil && !IsNil(o.Worm) {
		return true
	}

	return false
}

// SetWorm gets a reference to the given bool and assigns it to the Worm field.
func (o *BucketFlag) SetWorm(v bool) {
	o.Worm = &v
}

func (o BucketFlag) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BucketFlag) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeleteTriggerArchiveTier) {
		toSerialize["delete_trigger_archive_tier"] = o.DeleteTriggerArchiveTier
	}
	if !IsNil(o.GetTriggerRestore) {
		toSerialize["get_trigger_restore"] = o.GetTriggerRestore
	}
	if !IsNil(o.Readonly) {
		toSerialize["readonly"] = o.Readonly
	}
	if !IsNil(o.Recycle) {
		toSerialize["recycle"] = o.Recycle
	}
	if !IsNil(o.TierCache) {
		toSerialize["tier_cache"] = o.TierCache
	}
	if !IsNil(o.TierRetainExternalObject) {
		toSerialize["tier_retain_external_object"] = o.TierRetainExternalObject
	}
	if !IsNil(o.TierWorm) {
		toSerialize["tier_worm"] = o.TierWorm
	}
	if !IsNil(o.Versioned) {
		toSerialize["versioned"] = o.Versioned
	}
	if !IsNil(o.VersionsSuspended) {
		toSerialize["versions_suspended"] = o.VersionsSuspended
	}
	if !IsNil(o.Worm) {
		toSerialize["worm"] = o.Worm
	}
	return toSerialize, nil
}

type NullableBucketFlag struct {
	value *BucketFlag
	isSet bool
}

func (v NullableBucketFlag) Get() *BucketFlag {
	return v.value
}

func (v *NullableBucketFlag) Set(val *BucketFlag) {
	v.value = val
	v.isSet = true
}

func (v NullableBucketFlag) IsSet() bool {
	return v.isSet
}

func (v *NullableBucketFlag) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBucketFlag(val *BucketFlag) *NullableBucketFlag {
	return &NullableBucketFlag{value: val, isSet: true}
}

func (v NullableBucketFlag) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBucketFlag) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


