/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetadataClusterUpdatePrimaryDcReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataClusterUpdatePrimaryDcReq{}

// MetadataClusterUpdatePrimaryDcReq struct for MetadataClusterUpdatePrimaryDcReq
type MetadataClusterUpdatePrimaryDcReq struct {
	MetadataCluster *MetadataClusterUpdatePrimaryDcReqMetadataCluster `json:"metadata_cluster,omitempty"`
}

// NewMetadataClusterUpdatePrimaryDcReq instantiates a new MetadataClusterUpdatePrimaryDcReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataClusterUpdatePrimaryDcReq() *MetadataClusterUpdatePrimaryDcReq {
	this := MetadataClusterUpdatePrimaryDcReq{}
	return &this
}

// NewMetadataClusterUpdatePrimaryDcReqWithDefaults instantiates a new MetadataClusterUpdatePrimaryDcReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataClusterUpdatePrimaryDcReqWithDefaults() *MetadataClusterUpdatePrimaryDcReq {
	this := MetadataClusterUpdatePrimaryDcReq{}
	return &this
}

// GetMetadataCluster returns the MetadataCluster field value if set, zero value otherwise.
func (o *MetadataClusterUpdatePrimaryDcReq) GetMetadataCluster() MetadataClusterUpdatePrimaryDcReqMetadataCluster {
	if o == nil || IsNil(o.MetadataCluster) {
		var ret MetadataClusterUpdatePrimaryDcReqMetadataCluster
		return ret
	}
	return *o.MetadataCluster
}

// GetMetadataClusterOk returns a tuple with the MetadataCluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataClusterUpdatePrimaryDcReq) GetMetadataClusterOk() (*MetadataClusterUpdatePrimaryDcReqMetadataCluster, bool) {
	if o == nil || IsNil(o.MetadataCluster) {
		return nil, false
	}
	return o.MetadataCluster, true
}

// HasMetadataCluster returns a boolean if a field has been set.
func (o *MetadataClusterUpdatePrimaryDcReq) HasMetadataCluster() bool {
	if o != nil && !IsNil(o.MetadataCluster) {
		return true
	}

	return false
}

// SetMetadataCluster gets a reference to the given MetadataClusterUpdatePrimaryDcReqMetadataCluster and assigns it to the MetadataCluster field.
func (o *MetadataClusterUpdatePrimaryDcReq) SetMetadataCluster(v MetadataClusterUpdatePrimaryDcReqMetadataCluster) {
	o.MetadataCluster = &v
}

func (o MetadataClusterUpdatePrimaryDcReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataClusterUpdatePrimaryDcReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetadataCluster) {
		toSerialize["metadata_cluster"] = o.MetadataCluster
	}
	return toSerialize, nil
}

type NullableMetadataClusterUpdatePrimaryDcReq struct {
	value *MetadataClusterUpdatePrimaryDcReq
	isSet bool
}

func (v NullableMetadataClusterUpdatePrimaryDcReq) Get() *MetadataClusterUpdatePrimaryDcReq {
	return v.value
}

func (v *NullableMetadataClusterUpdatePrimaryDcReq) Set(val *MetadataClusterUpdatePrimaryDcReq) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataClusterUpdatePrimaryDcReq) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataClusterUpdatePrimaryDcReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataClusterUpdatePrimaryDcReq(val *MetadataClusterUpdatePrimaryDcReq) *NullableMetadataClusterUpdatePrimaryDcReq {
	return &NullableMetadataClusterUpdatePrimaryDcReq{value: val, isSet: true}
}

func (v NullableMetadataClusterUpdatePrimaryDcReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataClusterUpdatePrimaryDcReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


