/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MetadataClusterSetStretchedReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetadataClusterSetStretchedReq{}

// MetadataClusterSetStretchedReq struct for MetadataClusterSetStretchedReq
type MetadataClusterSetStretchedReq struct {
	MetadataCluster *MetadataClusterSetStretchedReqMetadataCluster `json:"metadata_cluster,omitempty"`
}

// NewMetadataClusterSetStretchedReq instantiates a new MetadataClusterSetStretchedReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataClusterSetStretchedReq() *MetadataClusterSetStretchedReq {
	this := MetadataClusterSetStretchedReq{}
	return &this
}

// NewMetadataClusterSetStretchedReqWithDefaults instantiates a new MetadataClusterSetStretchedReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataClusterSetStretchedReqWithDefaults() *MetadataClusterSetStretchedReq {
	this := MetadataClusterSetStretchedReq{}
	return &this
}

// GetMetadataCluster returns the MetadataCluster field value if set, zero value otherwise.
func (o *MetadataClusterSetStretchedReq) GetMetadataCluster() MetadataClusterSetStretchedReqMetadataCluster {
	if o == nil || IsNil(o.MetadataCluster) {
		var ret MetadataClusterSetStretchedReqMetadataCluster
		return ret
	}
	return *o.MetadataCluster
}

// GetMetadataClusterOk returns a tuple with the MetadataCluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataClusterSetStretchedReq) GetMetadataClusterOk() (*MetadataClusterSetStretchedReqMetadataCluster, bool) {
	if o == nil || IsNil(o.MetadataCluster) {
		return nil, false
	}
	return o.MetadataCluster, true
}

// HasMetadataCluster returns a boolean if a field has been set.
func (o *MetadataClusterSetStretchedReq) HasMetadataCluster() bool {
	if o != nil && !IsNil(o.MetadataCluster) {
		return true
	}

	return false
}

// SetMetadataCluster gets a reference to the given MetadataClusterSetStretchedReqMetadataCluster and assigns it to the MetadataCluster field.
func (o *MetadataClusterSetStretchedReq) SetMetadataCluster(v MetadataClusterSetStretchedReqMetadataCluster) {
	o.MetadataCluster = &v
}

func (o MetadataClusterSetStretchedReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetadataClusterSetStretchedReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetadataCluster) {
		toSerialize["metadata_cluster"] = o.MetadataCluster
	}
	return toSerialize, nil
}

type NullableMetadataClusterSetStretchedReq struct {
	value *MetadataClusterSetStretchedReq
	isSet bool
}

func (v NullableMetadataClusterSetStretchedReq) Get() *MetadataClusterSetStretchedReq {
	return v.value
}

func (v *NullableMetadataClusterSetStretchedReq) Set(val *MetadataClusterSetStretchedReq) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataClusterSetStretchedReq) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataClusterSetStretchedReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataClusterSetStretchedReq(val *MetadataClusterSetStretchedReq) *NullableMetadataClusterSetStretchedReq {
	return &NullableMetadataClusterSetStretchedReq{value: val, isSet: true}
}

func (v NullableMetadataClusterSetStretchedReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataClusterSetStretchedReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


