/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlertsResolveReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertsResolveReq{}

// AlertsResolveReq struct for AlertsResolveReq
type AlertsResolveReq struct {
	Alerts AlertsResolveReqAlerts `json:"alerts"`
}

type _AlertsResolveReq AlertsResolveReq

// NewAlertsResolveReq instantiates a new AlertsResolveReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertsResolveReq(alerts AlertsResolveReqAlerts) *AlertsResolveReq {
	this := AlertsResolveReq{}
	this.Alerts = alerts
	return &this
}

// NewAlertsResolveReqWithDefaults instantiates a new AlertsResolveReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertsResolveReqWithDefaults() *AlertsResolveReq {
	this := AlertsResolveReq{}
	return &this
}

// GetAlerts returns the Alerts field value
func (o *AlertsResolveReq) GetAlerts() AlertsResolveReqAlerts {
	if o == nil {
		var ret AlertsResolveReqAlerts
		return ret
	}

	return o.Alerts
}

// GetAlertsOk returns a tuple with the Alerts field value
// and a boolean to check if the value has been set.
func (o *AlertsResolveReq) GetAlertsOk() (*AlertsResolveReqAlerts, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alerts, true
}

// SetAlerts sets field value
func (o *AlertsResolveReq) SetAlerts(v AlertsResolveReqAlerts) {
	o.Alerts = v
}

func (o AlertsResolveReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertsResolveReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alerts"] = o.Alerts
	return toSerialize, nil
}

func (o *AlertsResolveReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alerts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertsResolveReq := _AlertsResolveReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlertsResolveReq)

	if err != nil {
		return err
	}

	*o = AlertsResolveReq(varAlertsResolveReq)

	return err
}

type NullableAlertsResolveReq struct {
	value *AlertsResolveReq
	isSet bool
}

func (v NullableAlertsResolveReq) Get() *AlertsResolveReq {
	return v.value
}

func (v *NullableAlertsResolveReq) Set(val *AlertsResolveReq) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertsResolveReq) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertsResolveReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertsResolveReq(val *AlertsResolveReq) *NullableAlertsResolveReq {
	return &NullableAlertsResolveReq{value: val, isSet: true}
}

func (v NullableAlertsResolveReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertsResolveReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


