/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the S3LoadBalancerGroupUpdateReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &S3LoadBalancerGroupUpdateReq{}

// S3LoadBalancerGroupUpdateReq struct for S3LoadBalancerGroupUpdateReq
type S3LoadBalancerGroupUpdateReq struct {
	S3LoadBalancerGroup S3LoadBalancerGroupUpdateReqGroup `json:"s3_load_balancer_group"`
}

type _S3LoadBalancerGroupUpdateReq S3LoadBalancerGroupUpdateReq

// NewS3LoadBalancerGroupUpdateReq instantiates a new S3LoadBalancerGroupUpdateReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewS3LoadBalancerGroupUpdateReq(s3LoadBalancerGroup S3LoadBalancerGroupUpdateReqGroup) *S3LoadBalancerGroupUpdateReq {
	this := S3LoadBalancerGroupUpdateReq{}
	this.S3LoadBalancerGroup = s3LoadBalancerGroup
	return &this
}

// NewS3LoadBalancerGroupUpdateReqWithDefaults instantiates a new S3LoadBalancerGroupUpdateReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewS3LoadBalancerGroupUpdateReqWithDefaults() *S3LoadBalancerGroupUpdateReq {
	this := S3LoadBalancerGroupUpdateReq{}
	return &this
}

// GetS3LoadBalancerGroup returns the S3LoadBalancerGroup field value
func (o *S3LoadBalancerGroupUpdateReq) GetS3LoadBalancerGroup() S3LoadBalancerGroupUpdateReqGroup {
	if o == nil {
		var ret S3LoadBalancerGroupUpdateReqGroup
		return ret
	}

	return o.S3LoadBalancerGroup
}

// GetS3LoadBalancerGroupOk returns a tuple with the S3LoadBalancerGroup field value
// and a boolean to check if the value has been set.
func (o *S3LoadBalancerGroupUpdateReq) GetS3LoadBalancerGroupOk() (*S3LoadBalancerGroupUpdateReqGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.S3LoadBalancerGroup, true
}

// SetS3LoadBalancerGroup sets field value
func (o *S3LoadBalancerGroupUpdateReq) SetS3LoadBalancerGroup(v S3LoadBalancerGroupUpdateReqGroup) {
	o.S3LoadBalancerGroup = v
}

func (o S3LoadBalancerGroupUpdateReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o S3LoadBalancerGroupUpdateReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["s3_load_balancer_group"] = o.S3LoadBalancerGroup
	return toSerialize, nil
}

func (o *S3LoadBalancerGroupUpdateReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"s3_load_balancer_group",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varS3LoadBalancerGroupUpdateReq := _S3LoadBalancerGroupUpdateReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varS3LoadBalancerGroupUpdateReq)

	if err != nil {
		return err
	}

	*o = S3LoadBalancerGroupUpdateReq(varS3LoadBalancerGroupUpdateReq)

	return err
}

type NullableS3LoadBalancerGroupUpdateReq struct {
	value *S3LoadBalancerGroupUpdateReq
	isSet bool
}

func (v NullableS3LoadBalancerGroupUpdateReq) Get() *S3LoadBalancerGroupUpdateReq {
	return v.value
}

func (v *NullableS3LoadBalancerGroupUpdateReq) Set(val *S3LoadBalancerGroupUpdateReq) {
	v.value = val
	v.isSet = true
}

func (v NullableS3LoadBalancerGroupUpdateReq) IsSet() bool {
	return v.isSet
}

func (v *NullableS3LoadBalancerGroupUpdateReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableS3LoadBalancerGroupUpdateReq(val *S3LoadBalancerGroupUpdateReq) *NullableS3LoadBalancerGroupUpdateReq {
	return &NullableS3LoadBalancerGroupUpdateReq{value: val, isSet: true}
}

func (v NullableS3LoadBalancerGroupUpdateReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableS3LoadBalancerGroupUpdateReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


