/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the DfsQosRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DfsQosRecord{}

// DfsQosRecord DfsQosRecord combine DfsQos and DfsQosStat as API response
type DfsQosRecord struct {
	Cluster *ClusterNestview `json:"cluster,omitempty"`
	Create *time.Time `json:"create,omitempty"`
	DfsPath *DfsPath `json:"dfs_path,omitempty"`
	DfsQosPolicy *DfsQosPolicy `json:"dfs_qos_policy,omitempty"`
	DfsRootfs *DfsRootfs `json:"dfs_rootfs,omitempty"`
	Id *int64 `json:"id,omitempty"`
	IoStatus *string `json:"io_status,omitempty"`
	Status *string `json:"status,omitempty"`
	Update *time.Time `json:"update,omitempty"`
	HdfsNum *int64 `json:"hdfs_num,omitempty"`
	IsBucket *bool `json:"is_bucket,omitempty"`
	Path *string `json:"path,omitempty"`
	Samples []DfsQosStat `json:"samples,omitempty"`
	Shares []string `json:"shares,omitempty"`
}

// NewDfsQosRecord instantiates a new DfsQosRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDfsQosRecord() *DfsQosRecord {
	this := DfsQosRecord{}
	return &this
}

// NewDfsQosRecordWithDefaults instantiates a new DfsQosRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDfsQosRecordWithDefaults() *DfsQosRecord {
	this := DfsQosRecord{}
	return &this
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *DfsQosRecord) GetCluster() ClusterNestview {
	if o == nil || IsNil(o.Cluster) {
		var ret ClusterNestview
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetClusterOk() (*ClusterNestview, bool) {
	if o == nil || IsNil(o.Cluster) {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *DfsQosRecord) HasCluster() bool {
	if o != nil && !IsNil(o.Cluster) {
		return true
	}

	return false
}

// SetCluster gets a reference to the given ClusterNestview and assigns it to the Cluster field.
func (o *DfsQosRecord) SetCluster(v ClusterNestview) {
	o.Cluster = &v
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *DfsQosRecord) GetCreate() time.Time {
	if o == nil || IsNil(o.Create) {
		var ret time.Time
		return ret
	}
	return *o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetCreateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Create) {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *DfsQosRecord) HasCreate() bool {
	if o != nil && !IsNil(o.Create) {
		return true
	}

	return false
}

// SetCreate gets a reference to the given time.Time and assigns it to the Create field.
func (o *DfsQosRecord) SetCreate(v time.Time) {
	o.Create = &v
}

// GetDfsPath returns the DfsPath field value if set, zero value otherwise.
func (o *DfsQosRecord) GetDfsPath() DfsPath {
	if o == nil || IsNil(o.DfsPath) {
		var ret DfsPath
		return ret
	}
	return *o.DfsPath
}

// GetDfsPathOk returns a tuple with the DfsPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetDfsPathOk() (*DfsPath, bool) {
	if o == nil || IsNil(o.DfsPath) {
		return nil, false
	}
	return o.DfsPath, true
}

// HasDfsPath returns a boolean if a field has been set.
func (o *DfsQosRecord) HasDfsPath() bool {
	if o != nil && !IsNil(o.DfsPath) {
		return true
	}

	return false
}

// SetDfsPath gets a reference to the given DfsPath and assigns it to the DfsPath field.
func (o *DfsQosRecord) SetDfsPath(v DfsPath) {
	o.DfsPath = &v
}

// GetDfsQosPolicy returns the DfsQosPolicy field value if set, zero value otherwise.
func (o *DfsQosRecord) GetDfsQosPolicy() DfsQosPolicy {
	if o == nil || IsNil(o.DfsQosPolicy) {
		var ret DfsQosPolicy
		return ret
	}
	return *o.DfsQosPolicy
}

// GetDfsQosPolicyOk returns a tuple with the DfsQosPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetDfsQosPolicyOk() (*DfsQosPolicy, bool) {
	if o == nil || IsNil(o.DfsQosPolicy) {
		return nil, false
	}
	return o.DfsQosPolicy, true
}

// HasDfsQosPolicy returns a boolean if a field has been set.
func (o *DfsQosRecord) HasDfsQosPolicy() bool {
	if o != nil && !IsNil(o.DfsQosPolicy) {
		return true
	}

	return false
}

// SetDfsQosPolicy gets a reference to the given DfsQosPolicy and assigns it to the DfsQosPolicy field.
func (o *DfsQosRecord) SetDfsQosPolicy(v DfsQosPolicy) {
	o.DfsQosPolicy = &v
}

// GetDfsRootfs returns the DfsRootfs field value if set, zero value otherwise.
func (o *DfsQosRecord) GetDfsRootfs() DfsRootfs {
	if o == nil || IsNil(o.DfsRootfs) {
		var ret DfsRootfs
		return ret
	}
	return *o.DfsRootfs
}

// GetDfsRootfsOk returns a tuple with the DfsRootfs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetDfsRootfsOk() (*DfsRootfs, bool) {
	if o == nil || IsNil(o.DfsRootfs) {
		return nil, false
	}
	return o.DfsRootfs, true
}

// HasDfsRootfs returns a boolean if a field has been set.
func (o *DfsQosRecord) HasDfsRootfs() bool {
	if o != nil && !IsNil(o.DfsRootfs) {
		return true
	}

	return false
}

// SetDfsRootfs gets a reference to the given DfsRootfs and assigns it to the DfsRootfs field.
func (o *DfsQosRecord) SetDfsRootfs(v DfsRootfs) {
	o.DfsRootfs = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DfsQosRecord) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DfsQosRecord) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *DfsQosRecord) SetId(v int64) {
	o.Id = &v
}

// GetIoStatus returns the IoStatus field value if set, zero value otherwise.
func (o *DfsQosRecord) GetIoStatus() string {
	if o == nil || IsNil(o.IoStatus) {
		var ret string
		return ret
	}
	return *o.IoStatus
}

// GetIoStatusOk returns a tuple with the IoStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetIoStatusOk() (*string, bool) {
	if o == nil || IsNil(o.IoStatus) {
		return nil, false
	}
	return o.IoStatus, true
}

// HasIoStatus returns a boolean if a field has been set.
func (o *DfsQosRecord) HasIoStatus() bool {
	if o != nil && !IsNil(o.IoStatus) {
		return true
	}

	return false
}

// SetIoStatus gets a reference to the given string and assigns it to the IoStatus field.
func (o *DfsQosRecord) SetIoStatus(v string) {
	o.IoStatus = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DfsQosRecord) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DfsQosRecord) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DfsQosRecord) SetStatus(v string) {
	o.Status = &v
}

// GetUpdate returns the Update field value if set, zero value otherwise.
func (o *DfsQosRecord) GetUpdate() time.Time {
	if o == nil || IsNil(o.Update) {
		var ret time.Time
		return ret
	}
	return *o.Update
}

// GetUpdateOk returns a tuple with the Update field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetUpdateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Update) {
		return nil, false
	}
	return o.Update, true
}

// HasUpdate returns a boolean if a field has been set.
func (o *DfsQosRecord) HasUpdate() bool {
	if o != nil && !IsNil(o.Update) {
		return true
	}

	return false
}

// SetUpdate gets a reference to the given time.Time and assigns it to the Update field.
func (o *DfsQosRecord) SetUpdate(v time.Time) {
	o.Update = &v
}

// GetHdfsNum returns the HdfsNum field value if set, zero value otherwise.
func (o *DfsQosRecord) GetHdfsNum() int64 {
	if o == nil || IsNil(o.HdfsNum) {
		var ret int64
		return ret
	}
	return *o.HdfsNum
}

// GetHdfsNumOk returns a tuple with the HdfsNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetHdfsNumOk() (*int64, bool) {
	if o == nil || IsNil(o.HdfsNum) {
		return nil, false
	}
	return o.HdfsNum, true
}

// HasHdfsNum returns a boolean if a field has been set.
func (o *DfsQosRecord) HasHdfsNum() bool {
	if o != nil && !IsNil(o.HdfsNum) {
		return true
	}

	return false
}

// SetHdfsNum gets a reference to the given int64 and assigns it to the HdfsNum field.
func (o *DfsQosRecord) SetHdfsNum(v int64) {
	o.HdfsNum = &v
}

// GetIsBucket returns the IsBucket field value if set, zero value otherwise.
func (o *DfsQosRecord) GetIsBucket() bool {
	if o == nil || IsNil(o.IsBucket) {
		var ret bool
		return ret
	}
	return *o.IsBucket
}

// GetIsBucketOk returns a tuple with the IsBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetIsBucketOk() (*bool, bool) {
	if o == nil || IsNil(o.IsBucket) {
		return nil, false
	}
	return o.IsBucket, true
}

// HasIsBucket returns a boolean if a field has been set.
func (o *DfsQosRecord) HasIsBucket() bool {
	if o != nil && !IsNil(o.IsBucket) {
		return true
	}

	return false
}

// SetIsBucket gets a reference to the given bool and assigns it to the IsBucket field.
func (o *DfsQosRecord) SetIsBucket(v bool) {
	o.IsBucket = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *DfsQosRecord) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *DfsQosRecord) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *DfsQosRecord) SetPath(v string) {
	o.Path = &v
}

// GetSamples returns the Samples field value if set, zero value otherwise.
func (o *DfsQosRecord) GetSamples() []DfsQosStat {
	if o == nil || IsNil(o.Samples) {
		var ret []DfsQosStat
		return ret
	}
	return o.Samples
}

// GetSamplesOk returns a tuple with the Samples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetSamplesOk() ([]DfsQosStat, bool) {
	if o == nil || IsNil(o.Samples) {
		return nil, false
	}
	return o.Samples, true
}

// HasSamples returns a boolean if a field has been set.
func (o *DfsQosRecord) HasSamples() bool {
	if o != nil && !IsNil(o.Samples) {
		return true
	}

	return false
}

// SetSamples gets a reference to the given []DfsQosStat and assigns it to the Samples field.
func (o *DfsQosRecord) SetSamples(v []DfsQosStat) {
	o.Samples = v
}

// GetShares returns the Shares field value if set, zero value otherwise.
func (o *DfsQosRecord) GetShares() []string {
	if o == nil || IsNil(o.Shares) {
		var ret []string
		return ret
	}
	return o.Shares
}

// GetSharesOk returns a tuple with the Shares field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DfsQosRecord) GetSharesOk() ([]string, bool) {
	if o == nil || IsNil(o.Shares) {
		return nil, false
	}
	return o.Shares, true
}

// HasShares returns a boolean if a field has been set.
func (o *DfsQosRecord) HasShares() bool {
	if o != nil && !IsNil(o.Shares) {
		return true
	}

	return false
}

// SetShares gets a reference to the given []string and assigns it to the Shares field.
func (o *DfsQosRecord) SetShares(v []string) {
	o.Shares = v
}

func (o DfsQosRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DfsQosRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Cluster) {
		toSerialize["cluster"] = o.Cluster
	}
	if !IsNil(o.Create) {
		toSerialize["create"] = o.Create
	}
	if !IsNil(o.DfsPath) {
		toSerialize["dfs_path"] = o.DfsPath
	}
	if !IsNil(o.DfsQosPolicy) {
		toSerialize["dfs_qos_policy"] = o.DfsQosPolicy
	}
	if !IsNil(o.DfsRootfs) {
		toSerialize["dfs_rootfs"] = o.DfsRootfs
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IoStatus) {
		toSerialize["io_status"] = o.IoStatus
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Update) {
		toSerialize["update"] = o.Update
	}
	if !IsNil(o.HdfsNum) {
		toSerialize["hdfs_num"] = o.HdfsNum
	}
	if !IsNil(o.IsBucket) {
		toSerialize["is_bucket"] = o.IsBucket
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Samples) {
		toSerialize["samples"] = o.Samples
	}
	if !IsNil(o.Shares) {
		toSerialize["shares"] = o.Shares
	}
	return toSerialize, nil
}

type NullableDfsQosRecord struct {
	value *DfsQosRecord
	isSet bool
}

func (v NullableDfsQosRecord) Get() *DfsQosRecord {
	return v.value
}

func (v *NullableDfsQosRecord) Set(val *DfsQosRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableDfsQosRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableDfsQosRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDfsQosRecord(val *DfsQosRecord) *NullableDfsQosRecord {
	return &NullableDfsQosRecord{value: val, isSet: true}
}

func (v NullableDfsQosRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDfsQosRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


