/*
XMS API

XMS is the controller of distributed storage system

API version: XSCALEROS_6.4.000.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NetworkInterfaceSamplesResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkInterfaceSamplesResp{}

// NetworkInterfaceSamplesResp struct for NetworkInterfaceSamplesResp
type NetworkInterfaceSamplesResp struct {
	NetworkInterfaceSamples []NetworkInterfaceStat `json:"network_interface_samples,omitempty"`
}

// NewNetworkInterfaceSamplesResp instantiates a new NetworkInterfaceSamplesResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkInterfaceSamplesResp() *NetworkInterfaceSamplesResp {
	this := NetworkInterfaceSamplesResp{}
	return &this
}

// NewNetworkInterfaceSamplesRespWithDefaults instantiates a new NetworkInterfaceSamplesResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkInterfaceSamplesRespWithDefaults() *NetworkInterfaceSamplesResp {
	this := NetworkInterfaceSamplesResp{}
	return &this
}

// GetNetworkInterfaceSamples returns the NetworkInterfaceSamples field value if set, zero value otherwise.
func (o *NetworkInterfaceSamplesResp) GetNetworkInterfaceSamples() []NetworkInterfaceStat {
	if o == nil || IsNil(o.NetworkInterfaceSamples) {
		var ret []NetworkInterfaceStat
		return ret
	}
	return o.NetworkInterfaceSamples
}

// GetNetworkInterfaceSamplesOk returns a tuple with the NetworkInterfaceSamples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkInterfaceSamplesResp) GetNetworkInterfaceSamplesOk() ([]NetworkInterfaceStat, bool) {
	if o == nil || IsNil(o.NetworkInterfaceSamples) {
		return nil, false
	}
	return o.NetworkInterfaceSamples, true
}

// HasNetworkInterfaceSamples returns a boolean if a field has been set.
func (o *NetworkInterfaceSamplesResp) HasNetworkInterfaceSamples() bool {
	if o != nil && !IsNil(o.NetworkInterfaceSamples) {
		return true
	}

	return false
}

// SetNetworkInterfaceSamples gets a reference to the given []NetworkInterfaceStat and assigns it to the NetworkInterfaceSamples field.
func (o *NetworkInterfaceSamplesResp) SetNetworkInterfaceSamples(v []NetworkInterfaceStat) {
	o.NetworkInterfaceSamples = v
}

func (o NetworkInterfaceSamplesResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkInterfaceSamplesResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkInterfaceSamples) {
		toSerialize["network_interface_samples"] = o.NetworkInterfaceSamples
	}
	return toSerialize, nil
}

type NullableNetworkInterfaceSamplesResp struct {
	value *NetworkInterfaceSamplesResp
	isSet bool
}

func (v NullableNetworkInterfaceSamplesResp) Get() *NetworkInterfaceSamplesResp {
	return v.value
}

func (v *NullableNetworkInterfaceSamplesResp) Set(val *NetworkInterfaceSamplesResp) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkInterfaceSamplesResp) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkInterfaceSamplesResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkInterfaceSamplesResp(val *NetworkInterfaceSamplesResp) *NullableNetworkInterfaceSamplesResp {
	return &NullableNetworkInterfaceSamplesResp{value: val, isSet: true}
}

func (v NullableNetworkInterfaceSamplesResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkInterfaceSamplesResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


